name: flutter_thermal_printer
description: "A Flutter plugin for printing on a STAR Micronics thermal printer."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  logging: ^1.0.2
  pair: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 7.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.iconica.flutter_thermal_printer
        pluginClass: PluginController
      ios:
        pluginClass: FlutterThermalPrinterPlugin

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
